/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package edu.stanford.junction.sample.tower_defense;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bullet=0x7f020000;
        public static final int explosion=0x7f020001;
        public static final int grass1=0x7f020002;
        public static final int grass2=0x7f020003;
        public static final int grass3=0x7f020004;
        public static final int icon=0x7f020005;
        public static final int obstacle1=0x7f020006;
        public static final int tank=0x7f020007;
        public static final int tank1=0x7f020008;
        public static final int tank2=0x7f020009;
        public static final int tank3=0x7f02000a;
        public static final int tank4=0x7f02000b;
        public static final int tank5=0x7f02000c;
        public static final int tank_aemon=0x7f02000d;
    }
    public static final class id {
        public static final int game=0x7f060000;
        public static final int text=0x7f060001;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int topping_item=0x7f030001;
    }
    public static final class raw {
        public static final int explosion=0x7f040000;
        public static final int shot=0x7f040001;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int game_layout_text_text=0x7f050001;
    }
}
